parameters:

  app_version: "1.3.7"
  
  app_name: "E-hub"
  full_app_name: "E-hub"
  no_reply: "no-reply@e-hub.khalilleo.com"

  webmasterName: "Webmaster"
  webmasterEmail: "demo@khalilleo.com"

  phoneNumber: '0163/616-5396'
  supportEmail: 'help@khalilleo.com'
  infoEmail: 'info@khalilleo.com'
  legalEmail: 'legal@khalilleo.com'

  addressStreet: 'Paul-Gerhardt-Str. 7'
  addressPlz: '74321'
  addressCity: 'Bietigheim-Bissingen'
  addressCountry: 'Deutschland'
  
  app_author: "Khalilleo Teams"
  app_created: "2024-06-22"
  app_made_by: "khalilleo.com"